Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import mysql.connector

# Koneksi ke MySQL
mysql_conn = mysql.connector.connect(
    host="irismysql-2739-irismysql-2739.l.aivencloud.com",  # Ganti dengan host MySQL Anda
    user="avnadmin",       # Ganti dengan username Anda
    password="AVNS_dO1A9DrK7DsaNfwz8pv", # Ganti dengan password Anda
    database="irismysql-2739",  # Ganti dengan nama database MySQL Anda
    port=19667,  # Tentukan port yang diinginkan (19667)
)

# Membuat cursor
mysql_cursor = mysql_conn.cursor()

# Mengambil data dari MySQL
mysql_query = "SELECT * FROM irismysql_2739"  # Ganti dengan query Anda
mysql_cursor.execute(mysql_query)
mysql_data = mysql_cursor.fetchall()
print(mysql_data)
------------------


[31m---------------------------------------------------------------------------[39m
[31mMySQLInterfaceError[39m                       Traceback (most recent call last)
[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/site-packages/mysql/connector/connection_cext.py:354[39m, in [36mCMySQLConnection._open_connection[39m[34m(self)[39m
[32m    353[39m [38;5;28;01mtry[39;00m:
[32m--> [39m[32m354[39m     [38;5;28;43mself[39;49m[43m.[49m[43m_cmysql[49m[43m.[49m[43mconnect[49m[43m([49m[43m*[49m[43m*[49m[43mcnx_kwargs[49m[43m)[49m
[32m    355[39m     [38;5;28mself[39m._cmysql.converter_str_fallback = [38;5;28mself[39m._converter_str_fallback

[31mMySQLInterfaceError[39m: Unknown MySQL server host 'irismysql-2739-irismysql-2739.l.aivencloud.com' (-2)

The above exception was the direct cause of the following exception:

[31mDatabaseError[39m                             Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[3][39m[32m, line 4[39m
[32m      1[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mmysql[39;00m[34;01m.[39;00m[34;01mconnector[39;00m
[32m      3[39m [38;5;66;03m# Koneksi ke MySQL[39;00m
[32m----> [39m[32m4[39m mysql_conn = [43mmysql[49m[43m.[49m[43mconnector[49m[43m.[49m[43mconnect[49m[43m([49m
[32m      5[39m [43m    [49m[43mhost[49m[43m=[49m[33;43m"[39;49m[33;43mirismysql-2739-irismysql-2739.l.aivencloud.com[39;49m[33;43m"[39;49m[43m,[49m[43m  [49m[38;5;66;43;03m# Ganti dengan host MySQL Anda[39;49;00m
[32m      6[39m [43m    [49m[43muser[49m[43m=[49m[33;43m"[39;49m[33;43mavnadmin[39;49m[33;43m"[39;49m[43m,[49m[43m       [49m[38;5;66;43;03m# Ganti dengan username Anda[39;49;00m
[32m      7[39m [43m    [49m[43mpassword[49m[43m=[49m[33;43m"[39;49m[33;43mAVNS_dO1A9DrK7DsaNfwz8pv[39;49m[33;43m"[39;49m[43m,[49m[43m [49m[38;5;66;43;03m# Ganti dengan password Anda[39;49;00m
[32m      8[39m [43m    [49m[43mdatabase[49m[43m=[49m[33;43m"[39;49m[33;43mirismysql-2739[39;49m[33;43m"[39;49m[43m,[49m[43m  [49m[38;5;66;43;03m# Ganti dengan nama database MySQL Anda[39;49;00m
[32m      9[39m [43m    [49m[43mport[49m[43m=[49m[32;43m19667[39;49m[43m,[49m[43m  [49m[38;5;66;43;03m# Tentukan port yang diinginkan (19667)[39;49;00m
[32m     10[39m [43m)[49m
[32m     12[39m [38;5;66;03m# Membuat cursor[39;00m
[32m     13[39m mysql_cursor = mysql_conn.cursor()

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/site-packages/mysql/connector/pooling.py:322[39m, in [36mconnect[39m[34m(*args, **kwargs)[39m
[32m    319[39m         [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(ERROR_NO_CEXT)
[32m    321[39m [38;5;28;01mif[39;00m CMySQLConnection [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m use_pure:
[32m--> [39m[32m322[39m     [38;5;28;01mreturn[39;00m [43mCMySQLConnection[49m[43m([49m[43m*[49m[43margs[49m[43m,[49m[43m [49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m
[32m    323[39m [38;5;28;01mreturn[39;00m MySQLConnection(*args, **kwargs)

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/site-packages/mysql/connector/connection_cext.py:142[39m, in [36mCMySQLConnection.__init__[39m[34m(self, **kwargs)[39m
[32m    140[39m [38;5;28;01mif[39;00m kwargs:
[32m    141[39m     [38;5;28;01mtry[39;00m:
[32m--> [39m[32m142[39m         [38;5;28;43mself[39;49m[43m.[49m[43mconnect[49m[43m([49m[43m*[49m[43m*[49m[43mkwargs[49m[43m)[49m
[32m    143[39m     [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[32m    144[39m         [38;5;28mself[39m.close()

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/site-packages/mysql/connector/abstracts.py:1605[39m, in [36mMySQLConnectionAbstract.connect[39m[34m(self, **kwargs)[39m
[32m   1602[39m     [38;5;28mself[39m.config(**kwargs)
[32m   1604[39m [38;5;28mself[39m.disconnect()
[32m-> [39m[32m1605[39m [38;5;28;43mself[39;49m[43m.[49m[43m_open_connection[49m[43m([49m[43m)[49m
[32m   1607[39m charset, collation = (
[32m   1608[39m     kwargs.pop([33m"[39m[33mcharset[39m[33m"[39m, [38;5;28;01mNone[39;00m),
[32m   1609[39m     kwargs.pop([33m"[39m[33mcollation[39m[33m"[39m, [38;5;28;01mNone[39;00m),
[32m   1610[39m )
[32m   1611[39m [38;5;28;01mif[39;00m charset [38;5;129;01mor[39;00m collation:

[36mFile [39m[32m/usr/local/python/3.12.1/lib/python3.12/site-packages/mysql/connector/connection_cext.py:360[39m, in [36mCMySQLConnection._open_connection[39m[34m(self)[39m
[32m    358[39m [38;5;28;01mexcept[39;00m MySQLInterfaceError [38;5;28;01mas[39;00m err:
[32m    359[39m     [38;5;28;01mif[39;00m [38;5;28mhasattr[39m(err, [33m"[39m[33merrno[39m[33m"[39m):
[32m--> [39m[32m360[39m         [38;5;28;01mraise[39;00m get_mysql_exception(
[32m    361[39m             err.errno, msg=err.msg, sqlstate=err.sqlstate
[32m    362[39m         ) [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01merr[39;00m
[32m    363[39m     [38;5;28;01mraise[39;00m InterfaceError([38;5;28mstr[39m(err)) [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01merr[39;00m
[32m    365[39m [38;5;28mself[39m._do_handshake()

[31mDatabaseError[39m: 2005 (HY000): Unknown MySQL server host 'irismysql-2739-irismysql-2739.l.aivencloud.com' (-2)

