Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import mysql.connector

# Koneksi ke MySQL
mysql_conn = mysql.connector.connect(
    host="irismysql-2739-irismysql-2739.l.aivencloud.com",  # Ganti dengan host MySQL Anda
    user="avnadmin",       # Ganti dengan username Anda
    password="AVNS_dO1A9DrK7DsaNfwz8pv", # Ganti dengan password Anda
    database="irismysql-2739",  # Ganti dengan nama database MySQL Anda
    port=19667,  # Tentukan port yang diinginkan (19667)
)

# Membuat cursor
mysql_cursor = mysql_conn.cursor()

# Mengambil data dari MySQL
mysql_query = "SELECT * FROM irismysql_2739"  # Ganti dengan query Anda
mysql_cursor.execute(mysql_query)
mysql_data = mysql_cursor.fetchall()
print(mysql_data)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mMySQLInterfaceError[0m                       Traceback (most recent call last)
File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/mysql/connector/connection_cext.py:365[0m, in [0;36mCMySQLConnection._open_connection[0;34m(self)[0m
[1;32m    364[0m [38;5;28;01mtry[39;00m:
[0;32m--> 365[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_cmysql[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcnx_kwargs[49m[43m)[49m
[1;32m    366[0m     [38;5;28mself[39m[38;5;241m.[39m_cmysql[38;5;241m.[39mconverter_str_fallback [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_converter_str_fallback

[0;31mMySQLInterfaceError[0m: Unknown MySQL server host 'irismysql-2739-irismysql-2739.l.aivencloud.com' (-2)

The above exception was the direct cause of the following exception:

[0;31mDatabaseError[0m                             Traceback (most recent call last)
Cell [0;32mIn[3], line 4[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mmysql[39;00m[38;5;21;01m.[39;00m[38;5;21;01mconnector[39;00m
[1;32m      3[0m [38;5;66;03m# Koneksi ke MySQL[39;00m
[0;32m----> 4[0m mysql_conn [38;5;241m=[39m [43mmysql[49m[38;5;241;43m.[39;49m[43mconnector[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m
[1;32m      5[0m [43m    [49m[43mhost[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mirismysql-2739-irismysql-2739.l.aivencloud.com[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m  [49m[38;5;66;43;03m# Ganti dengan host MySQL Anda[39;49;00m
[1;32m      6[0m [43m    [49m[43muser[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mavnadmin[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m       [49m[38;5;66;43;03m# Ganti dengan username Anda[39;49;00m
[1;32m      7[0m [43m    [49m[43mpassword[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mAVNS_dO1A9DrK7DsaNfwz8pv[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;66;43;03m# Ganti dengan password Anda[39;49;00m
[1;32m      8[0m [43m    [49m[43mdatabase[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mirismysql-2739[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m  [49m[38;5;66;43;03m# Ganti dengan nama database MySQL Anda[39;49;00m
[1;32m      9[0m [43m    [49m[43mport[49m[38;5;241;43m=[39;49m[38;5;241;43m19667[39;49m[43m,[49m[43m  [49m[38;5;66;43;03m# Tentukan port yang diinginkan (19667)[39;49;00m
[1;32m     10[0m [43m)[49m
[1;32m     12[0m [38;5;66;03m# Membuat cursor[39;00m
[1;32m     13[0m mysql_cursor [38;5;241m=[39m mysql_conn[38;5;241m.[39mcursor()

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/mysql/connector/pooling.py:322[0m, in [0;36mconnect[0;34m(*args, **kwargs)[0m
[1;32m    319[0m         [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(ERROR_NO_CEXT)
[1;32m    321[0m [38;5;28;01mif[39;00m CMySQLConnection [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m use_pure:
[0;32m--> 322[0m     [38;5;28;01mreturn[39;00m [43mCMySQLConnection[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    323[0m [38;5;28;01mreturn[39;00m MySQLConnection([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/mysql/connector/connection_cext.py:153[0m, in [0;36mCMySQLConnection.__init__[0;34m(self, **kwargs)[0m
[1;32m    151[0m [38;5;28;01mif[39;00m kwargs:
[1;32m    152[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 153[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    154[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[1;32m    155[0m         [38;5;28mself[39m[38;5;241m.[39mclose()

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/mysql/connector/abstracts.py:1529[0m, in [0;36mMySQLConnectionAbstract.connect[0;34m(self, **kwargs)[0m
[1;32m   1526[0m     [38;5;28mself[39m[38;5;241m.[39mconfig([38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m   1528[0m [38;5;28mself[39m[38;5;241m.[39mdisconnect()
[0;32m-> 1529[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_open_connection[49m[43m([49m[43m)[49m
[1;32m   1531[0m charset, collation [38;5;241m=[39m (
[1;32m   1532[0m     kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124mcharset[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m),
[1;32m   1533[0m     kwargs[38;5;241m.[39mpop([38;5;124m"[39m[38;5;124mcollation[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m),
[1;32m   1534[0m )
[1;32m   1535[0m [38;5;28;01mif[39;00m charset [38;5;129;01mor[39;00m collation:

File [0;32m/usr/local/python/3.12.1/lib/python3.12/site-packages/mysql/connector/connection_cext.py:370[0m, in [0;36mCMySQLConnection._open_connection[0;34m(self)[0m
[1;32m    368[0m         [38;5;28mself[39m[38;5;241m.[39mconverter[38;5;241m.[39mstr_fallback [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_converter_str_fallback
[1;32m    369[0m [38;5;28;01mexcept[39;00m MySQLInterfaceError [38;5;28;01mas[39;00m err:
[0;32m--> 370[0m     [38;5;28;01mraise[39;00m get_mysql_exception(
[1;32m    371[0m         msg[38;5;241m=[39merr[38;5;241m.[39mmsg, errno[38;5;241m=[39merr[38;5;241m.[39merrno, sqlstate[38;5;241m=[39merr[38;5;241m.[39msqlstate
[1;32m    372[0m     ) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m    374[0m [38;5;28mself[39m[38;5;241m.[39m_do_handshake()
[1;32m    376[0m [38;5;28;01mif[39;00m (
[1;32m    377[0m     [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_ssl_disabled
[1;32m    378[0m     [38;5;129;01mand[39;00m [38;5;28mhasattr[39m([38;5;28mself[39m[38;5;241m.[39m_cmysql, [38;5;124m"[39m[38;5;124mget_ssl_cipher[39m[38;5;124m"[39m)
[0;32m   (...)[0m
[1;32m    383[0m 
[1;32m    384[0m     [38;5;66;03m# `get_ssl_cipher()` returns the name of the cipher being used.[39;00m

[0;31mDatabaseError[0m: 2005 (HY000): Unknown MySQL server host 'irismysql-2739-irismysql-2739.l.aivencloud.com' (-2)

